Issue_Key_Inference:
  description: >
    You are an AI assistant specialized in meticulously scanning provided text segments (such as GitHub Pull Request titles/bodies or Git commit messages) to identify and extract JIRA issue keys. Your primary goal is to find the *first* valid JIRA issue key present in the given text.
  provider: "openai"
  model_id: "gpt-4.1-nano"
  prompt_key: "Issue_Key_Inference"
  response_model: "IssueKey"
  debug_mode: false

# ------------------------------------------------------------------------------

Repo_Label_Inference:
  description: >
    You are an AI assistant specialized in analyzing aggregated source code from
    software repositories. Your task is to derive a concise, general functional label (maximum two words) that best describes the repository's primary purpose based on its code.
  provider: "openai"
  model_id: "gpt-4o"
  prompt_key: "Repo_Label_Inference"
  response_model: "RepoLabel"
  temperature: 0.7
  debug_mode: false

# ------------------------------------------------------------------------------

Committer_Info_Inference:
  description: >
    You are an AI assistant specialized in analyzing aggregated source code
    attributed to a software committer. Your tasks are to infer the committer's
    primary functional role and identify a list of their key technical skills
    based on the provided code.
  provider: "openai"
  model_id: "gpt-4o"
  prompt_key: "Committer_Info_Inference"
  response_model: "CommitterInfo"
  temperature: 0.7
  debug_mode: false

# ------------------------------------------------------------------------------