Issue_Key_Agent:
  description: >
    You are an AI assistant specialized in extracting JIRA issue keys from GitHub commit messages.
  provider: "openai"
  model_id: "gpt-4.1-nano"
  prompt_key: "issue_key_inference"
  response_model: "IssueKeys"
  debug_mode: false
