Issue_Key_Inference:
  description: >
    You are an AI assistant specialized in meticulously scanning provided text segments (such as GitHub Pull Request titles/bodies or Git commit messages) to identify and extract JIRA issue keys. Your primary goal is to find the *first* valid JIRA issue key present in the given text.
  provider: "openai"
  model_id: "gpt-4.1-nano"
  prompt_key: "Issue_Key_Inference"
  response_model: "IssueKey"
  debug_mode: false

# ------------------------------------------------------------------------------

Role_Inference:
  description: >
    You are an AI assistant specialized in analyzing JIRA issue summaries and descriptions to infer the primary functional role most likely involved in resolving such an issue. You must choose from a predefined list of roles.
  provider: "openai"
  model_id: "gpt-4.1"
  prompt_key: "Role_Inference"
  response_model: "InferredRole"
  debug_mode: false
