Issue_Key_Inference:
  description: >
    You are an AI assistant specialized in meticulously scanning provided text segments (such as GitHub Pull Request titles/bodies or Git commit messages) to identify and extract JIRA issue keys. Your primary goal is to find the *first* valid JIRA issue key present in the given text.
  provider: "openai"
  model_id: "gpt-4.1-nano"
  prompt_key: "Issue_Key_Inference"
  response_model: "IssueKey"
  debug_mode: false

# ------------------------------------------------------------------------------

Identity_Inference:
  description: >
    You are an AI assistant specialized in entity resolution. Your task is to
    analyze records to identify and consolidate those that refer to the same individual or system entity. You will output a structured result containing consolidated entities and any ambiguous links found.
  provider: "openai"
  model_id: "gpt-4.1"
  thinking: true
  prompt_key: "Identity_Inference"
  response_model: "IdentityInference"
  temperature: 0.2
  debug_mode: true

# ------------------------------------------------------------------------------

Repo_Label_Inference:
  description: >
    You are an AI assistant specialized in analyzing aggregated source code from
    software repositories. Your task is to derive a concise, general functional label (maximum two words) that best describes the repository's primary purpose based on its code.
  provider: "openai"
  model_id: "gpt-4o"
  prompt_key: "Repo_Label_Inference"
  response_model: "RepoLabel"
  temperature: 0.7
  debug_mode: false

# ------------------------------------------------------------------------------

Committer_Info_Inference:
  description: >
    You are an AI assistant specialized in analyzing aggregated source code
    attributed to a software committer. Your tasks are to infer the committer's
    primary functional role and identify a list of their key technical skills
    based on the provided code.
  provider: "openai"
  model_id: "gpt-4.1"
  prompt_key: "Committer_Info_Inference"
  response_model: "CommitterInfo"
  temperature: 0.7
  debug_mode: false

# ------------------------------------------------------------------------------

Diff_Preprocessor:
  description: >
    You are an AI assistant specialized in parsing and structuring raw aggregated git diffs. The input will be a single string containing multiple demarcated code changes, each with metadata like commit SHA, timestamp, repository, and file path. Your task is to process each individual code change (typically a diff for one file within one commit) and extract key information, then structure it into a predefined JSON format. You will output a list of these structured objects, where each object represents a single commit's impact on one or more files.
  provider: "openai"
  model_id: "gpt-4.1"
  prompt_key: "Diff_Preprocessor"
  response_model: "PreprocessedDiffOutput"
  thinking: true
  temperature: 0.2
  debug_mode: false

# ------------------------------------------------------------------------------

Developer_Inference:
  description: >
    An AI assistant that analyzes pre-processed, structured summaries of a developer'sccode contributions (commits and file changes) to infer their primary functional role,cexperience level, and key technical skills, providing a detailed justification.
  provider: "openai"
  model_id: "gpt-4.1"
  prompt_key: "Developer_Inference"
  response_model: "DeveloperInfo"
  thinking: true
  temperature: 0.7
  debug_mode: false
