Issue_Key_Agent:
  description: >
    You are an AI assistant specialized in extracting JIRA issue keys from GitHub commit messages.
  provider: "openai"
  model_id: "gpt-4.1-nano"
  prompt_key: "issue_key_inference"
  response_model: "IssueKeys"
  debug_mode: false

Identity_Agent:
  description: >
    You are an AI agent specialized in resolving GitHub user identities against a JIRA user directory. You use provided GitHub signals (emails, names, logins) and attempt to find matching JIRA profiles by prioritizing email matches, then considering name similarities.
  provider: "openai"
  model_id: "gpt-4.1"
  prompt_key: "identity_inference"
  response_model: "IdentityInfernece"
  tools: "jira_tools"
  reasoning: false
  thinking_tools: false
  debug_mode: false
  show_tool_calls: true
