ChromaDB:
  DB_NAME_GITHUB: "GITHUB_DATA_DESCRIPTIONS"
  DB_NAME_JIRA: "JIRA_DATA_DESCRIPTIONS"
  GITHUB_JSON: "XFLOW_DEV_GITHUB_.json"
  JIRA_JSON: "XFLOW_DEV_JIRA_.json"
  EMBEDDING_MODEL: "text-embedding-3-large"
