knowledgebase_query: >
  I need to plan SQL queries to extract all user identifying information from GitHub and JIRA.
  What schema details (tables, columns) should I be aware of from both platforms? 
  Retrieve this information from the knowledge base.

planner_query: >
  High-level Data Goal: Devise a comprehensive data retrieval strategy to identify unique individuals by collecting all relevant user identification attributes from our GitHub and JIRA data sources.
  Consider strategies for large tables (distinct user IDs, time-scoping).
  Based EXCLUSIVELY on the 'Provided Schema Information' and the 'High-level Data Goal', generate the 'SQLPlan' JSON object.
  Provided Schema Information:
    ```json
    {knowledgebase_info}
    ```

sql_constructor_query: >
  You are an SQL Query String Constructor. Based on your detailed instructions and the following 'SQLPlan' JSON object, generate a list of precise, executable SQL SELECT query strings.
  Ensure each query corresponds to a table in the plan, correctly applies column selections with aliases, and translates any query hints into valid, generally ANSI-compliant SQL clauses.
  Your output MUST be a JSON object conforming to the 'SQLQueries' structure, including carrying forward the 'plan_summary' and 'strategy_notes'.

  Input SQLPlan:
    ```json
    {sql_plan_json}
    ```

sql_executor_query: >
  You are a SQL Query Execution Specialist. Execute the following SQL query using your SQL execution tool and return the raw results.

  SQL Query to Execute:
    ```json
    {sql_query_json}
    ```

identity_query: >
  Perform identity resolution based on the following data. Data:
    ```json
    {sql_results}
    ```
