knowledgebase_query: >
  I need to plan SQL queries to extract all user identifying information from GitHub and JIRA.
  What schema details (tables, columns) should I be aware of from both platforms? 
  Retrieve this information from the knowledge base.

planner_query: >
  High-level Data Goal: Devise a comprehensive data retrieval strategy to identify unique individuals by collecting all relevant user identification attributes from our GitHub and JIRA data sources.
  Consider strategies for large tables (distinct user IDs, time-scoping).
  Based EXCLUSIVELY on the 'Provided Schema Information' and the 'High-level Data Goal', generate the 'SQLPlan' JSON object.
  Provided Schema Information:
    ```json
    {schema_info}
    ```

sql_query: >
  You are a SQL Query Execution Specialist. Your input is a detailed 'SQLPlan' JSON object.
  Your task is to:
  1. Meticulously follow your detailed instructions to process BOTH the 'github' and 'jira' sections of the provided 'SQLPlan'.
  2. For EACH table specified in the plan, construct the appropriate SQL SELECT statement based on the 'columns' (using 'source_field' and 'alias') and any 'table_query_hints' or 'platform_query_hints'.
  3. Execute EACH generated SQL query using the 'SQL execution tool'.
  4. Aggregate ALL results from all queries.
  5. Return a single JSON object strictly conforming to the 'SQLResults' structure, containing all retrieved data under 'github' and 'jira' keys within the 'results' object.

  Strictly adhere to the plan and your instructions. Do not infer or deviate.

  SQLPlan to execute:
    ```json
    {sql_plan}
    ```

identity_query: >
  Perform identity resolution based on the following data. Data:
    ```json
    {sql_results}
    ```
